import '@/styles/globals.css';
import Head from 'next/head';
import { Anuphan, Mitr } from 'next/font/google';

import styles from '@/styles/shared.module.css';

const mitr = Mitr({
  weight: ['400'],
  fallback: ['cursive'],
  variable: '--font-header',
  subsets: ['thai'],
});

const anuphan = Anuphan({
  weight: ['300', '600'],
  fallback: ['sans-serif'],
  variable: '--font-content',
  subsets: ['thai'],
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${anuphan.variable} ${mitr.variable}`}>
        <div className={styles.container}>
          <Component {...pageProps} />
        </div>
      </main>
    </>
  );
}
