import Head from 'next/head';

import Card from '@/components/Card';
import Answer from '@/components/Answer';

import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card className={styles.question}>
        <h2>
          🥔 เซอร์ไพรส์สติ๊กเกอร์ซัพพลายเออร์ แรงใจพ่อค้าท็อปบูตเซ็กซ์ เทค
          กรีนทอล์คหมายปองลาเต้คัตเอาต์ มะกัน เย้ว บอดี้บิ๊กเที่ยงวันรีสอร์ต ?
        </h2>
        <br />
        <br />
        <Answer>แอดมิสชันซามูไรเห่ย</Answer>
        <Answer>ไทม์โฮลวีตปัจฉิมนิเทศแอคทีฟ</Answer>
        <Answer>วีนโดมิโนแอ็คชั่นโนติส</Answer>
        <Answer>ผลไม้เป่ายิงฉุบริคเตอร์เหมยเพรส</Answer>
      </Card>
    </>
  );
}
